name: transitforecast

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.7
  - pip
  - astroplan
  - astropy
  - matplotlib
  - numpy
  - exoplanet
  - lightkurve
  - pymc3
  - scipy
  - theano
  - nbsphinx
  - numpydoc
  - sphinx-automodapi
  - pip:
    - transitleastsquares
